### ISSUE TITLE
Ambient light

### ISSUE THREAD

**Issue by vujadin** [jnsmalm/pixi3d#10]
I needed ambient light for a project so I've quickly implemented one: https://github.com/vujadin/pixi3d/tree/ambient-light
Here's the result: http://babylonhx.com/pixiambient/
Couldn't get the right result with other types of light and wasn't able to use image lighting because of a project size limit...
Would be nice to have something like this in the "official" Pixi3D.

**Comment by jnsmalm** [comment]
I went to http://babylonhx.com/pixiambient/ , is the issue that it's transparent?

**Comment by jnsmalm** [comment]
Not sure which problems you had, but using your code it works pretty well. Seems like you forgot one thing though, in standard-material.ts make sure you have the following code in "updateUniforms" function:

```
switch (light.type) {
        case LightType.point: type = 1; break
        case LightType.directional: type = 0; break
        case LightType.spot: type = 2; break
        case LightType.ambient: type = 3; break
      }
```

Also, it will make a difference depending on the settings of the material of the object (metallic and roughness).

I'll see if I can add ambient lighting in Pixi3D soon, let me know if you have additional issues.

**Comment by vujadin** [comment]
My code works just fine, no issues at all. I do have that part in "updateUniforms", it wouldn't work without it:
https://github.com/vujadin/pixi3d/commit/192a3edfb12ad6d9056d583e991acc09127dc2d8#diff-fc6cad664a018cca57b22da32546f5ce77ec793efc0910233439c2acca887e82

No issues at all, this was just a suggestion for adding ambient light to the framework. Closing this now...

**Comment by jnsmalm** [comment]
Thanks for the help, I added your implementation to the develop branch 👍

**Comment by tkmoney** [comment]
> Thanks for the help, I added your implementation to the develop branch 👍

You mention that you merged this in the dev branch but I don't see it there.
