### ISSUE TITLE
How to build 3D grid [ 10- 10 ] with racks on it

### ISSUE THREAD

**Issue by molchanov1983** [jnsmalm/pixi3d#101]
How to build 3D grid ? How to add rack inside grid?

**Comment by molchanov1983** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/5277449/173136282-00da7064-b8a9-4f94-a3a4-f2f33e3004d6.png)

**Comment by jnsmalm** [comment]
Use createPlane https://api.pixi3d.org/classes/Mesh3D.html#createPlane to create the grid  and apply a texture to it.

`material.baseTexture = PIXI.Texture.from(...)`

Use createCube https://api.pixi3d.org/classes/Mesh3D.html#createCube to create the boxes.
