### ISSUE TITLE
Cannot read properties of undefined (reading 'lights')

### ISSUE THREAD

**Issue by zz201276** [jnsmalm/pixi3d#130]
Copy the code of the example and find that it does not work. Downloading the example directly still does not work, and the same error is prompted.

![image](https://user-images.githubusercontent.com/50104871/191683907-f9e198f9-8c02-4de5-9cb7-95289a88f020.png)

![1663831429941](https://user-images.githubusercontent.com/50104871/191684057-0b20c9b6-9eac-4ee4-bde8-69845f60c2f3.png)

**Comment by jnsmalm** [comment]
How did you copy the code?

For me it works by doing:

1. git clone https://github.com/jnsmalm/pixi3d-sandbox.git
2. cd pixi3d-sandbox
3. npm install
4. npm start

**Comment by zz201276** [comment]
According to the process you said, I tried it again and ran the custom-geometry demo, which returned me a new error，I'm not quite sure why this is



![image](https://user-images.githubusercontent.com/50104871/191895848-e05975b8-1d14-430c-a437-3777c00f32cd.png)

**Comment by jnsmalm** [comment]
Sorry, I have no idea actually. Does "create-pixi3d-app work for you?" https://github.com/jnsmalm/pixi3d#getting-started
