### ISSUE TITLE
Migration to pixijs v7

### ISSUE THREAD

**Issue by cqh963852** [jnsmalm/pixi3d#138]
https://github.com/pixijs/pixijs/wiki/v7-Migration-Guide#-other-changes

AbstractBatchRenderer and BatchPluginFactory has been removed. Either extends BatchRenderer or use

And roadmap migration to pixijs v7?

**Comment by jnsmalm** [comment]
Pixi3D 2.0, with support for PixiJS v7 is now available. Please let me know if you have any issues.

**Comment by jnsmalm** [comment]
Also check the change log as there are breaking changes. https://github.com/jnsmalm/pixi3d/blob/develop/CHANGELOG.md

**Comment by cqh963852** [comment]
Can we add a readme from pixi3d/pixi7

Should import like this.

```
import * as PIXI3D from "pixi3d/pixi7";
```

**Comment by jnsmalm** [comment]
I already added this in the README, is it not enough?

If PixiJS v5 or v6 is used, import from pixi3d i.e. import { Model } from "pixi3d". If PixiJS v7 is used, instead import from pixi3d/pixi7 i.e. import { Model } from "pixi3d/pixi7".

**Comment by cqh963852** [comment]
> I already added this in the README, is it not enough?
> 
> If PixiJS v5 or v6 is used, import from pixi3d i.e. import { Model } from "pixi3d". If PixiJS v7 is used, instead import from pixi3d/pixi7 i.e. import { Model } from "pixi3d/pixi7".

Sorry, I missed that. Thanks a lot.
