### ISSUE TITLE
can't have multiple lights for shadows?

### ISSUE THREAD

**Issue by oibrah3q** [jnsmalm/pixi3d#142]
I've tried just about everything, but it looks like only one ShadowCastingLight can be enabled at a time. I've tried omitting the light from enableShadows and just include the mesh, thinking that if I included the light argument it would only generate shadows for that specific light, but it appears to do nothing at all. The documentation states that the second argument is optional. I've tried creating a shadow render pass and using addShadowCastingLight, I was able to see that I've added the render pass to the mesh, but I'm not sure if it calls. I tried brute force adding the shadow render pass to the main renderer's pipeline passes, but it looks like the shadow render pass that's created from ShadowRenderPass() uses version 300 shader code as opposed to the version 100 that the default shadow render pass is built with, and then causes an error.

Is it possible to have multiple shadow casting lights? I would appreciate any help on this, thank you.

**Comment by jnsmalm** [comment]
Standard material only supports a single light with shadows at the moment.
