### ISSUE TITLE
GLTF / GLB files with vertex colours are not rendered.

### ISSUE THREAD

**Issue by richo0** [jnsmalm/pixi3d#148]
Hi,

I just found your project from Hacker News, it's really awesome - thanks for creating this! 

I'm having issues loading GLTF files which use vertex colours, they do not render at all.

For example, the code below should render the cherry model in the attached image - however all I see is a black screen and no errors. I'm wondering if the standard fragment shader does not support vertex colours? 

Please find attached a zip file of the model attached.

I'd love to use your library on a project I'm working on, however all of the art assets use vertex colours. :-(

Any assistance you might provide would be most appreciated - I love what you've done here! 

Cheers,
-R

<img width="538" alt="Screenshot 2022-12-22 at 8 02 11 PM" src="https://user-images.githubusercontent.com/42013650/209207988-0e7ffc44-09fd-4a8b-bb06-59a72ac5e890.png">
`let app = new PIXI.Application({
		backgroundColor: 0x000000, resizeTo: window, antialias: true
		});
		document.body.appendChild(app.view);

		// Using a self executing function just to make the different methods more comparable.
		(async function load() {
		  let gltf = await PIXI.Assets.load("cherry.gltf")
		  setup(gltf)
		})()
		
		function setup(gltf) {
		   let mesh2 = app.stage.addChild(PIXI3D.Model.from(gltf));
		 
		    
		   mesh2.scale.set(1);
		   
		  
		   app.ticker.add(() => {
		   rotation=rotation+0.1
		   mesh2.rotationQuaternion.setEulerAngles(0, rotation,0 )
		
		   scale = scale + ds 
		   if (scale > 16){
			   ds=-ds
			   scale=scale+ds
		   }
		   if (scale < 0.01){
			   ds=-ds
			   scale=scale+ds
		   }
		//   mesh2.scale.set(-scale)
	
	//	   light.intensity=scale
		})
		}

		
		//let mesh = app.stage.addChild(PIXI3D.Mesh3D.createCube());
				
		let light = new PIXI3D.Light()
		light.position.set(0,0,50)
		light.range=100
		light.intensity=100
		PIXI3D.LightingEnvironment.main.lights.push(light)
		//mesh.position.y=-1
		let rotation = 0
		
		let scale = 1
		let ds = 0.01
		//let control = new CameraOrbitControl(app.view);
		//app.ticker.add(() => {
		//mesh.rotationQuaternion.setEulerAngles(rotation, rotation++,0 )
		//})`
[cherry.gltf.zip](https://github.com/jnsmalm/pixi3d/files/10289689/cherry.gltf.zip)

**Comment by jnsmalm** [comment]
Hello and thanks!

Vertex colors are supported with standard material.

There seems to be a bug in Pixi3D with that specific gltf file, doesn't want to render it for some reason - I'll investigate this. I tried importing the gltf file in Blender and then exporting it to gltf again and that file worked.

Thanks for reporting, I'll try to fix this as soon as I can.

**Comment by richo0** [comment]
Thanks for the quick reply!  Really looking forward to using this!

**Comment by jnsmalm** [comment]
Would it be ok with you if I use this model in automatic tests to make sure this issue won't come back?

**Comment by richo0** [comment]
Yes - no problem! Sent from my iPhoneOn 22 Dec 2022, at 9:09 PM, Jens Malmborg ***@***.***> wrote:﻿
Would it be ok with you if I use this model in automatic tests to make sure this issue won't come back?

**Comment by jnsmalm** [comment]
Created a new version 2.1.1, please let me know if this fixes your issue.

**Comment by richo0** [comment]
Works perfectly! Thank you very much!
