### ISSUE TITLE
Create Model3Ds from Submeshes?

### ISSUE THREAD

**Issue by JotFX** [jnsmalm/pixi3d#16]
Hi!
I am loading a GLTF with six dice models as separate meshes inside. That works well. But I need those 6 meshes as separate Models, because they must be animated independently.
Simply setting the transforms on the children of the model works somehow, but the lighting on the material is not updated while animating, besides other transformation issues ....
I tried something like 

const subModel = new PIXI3D.Model();
subModel.meshes.push(mesh.children[0].children[0]);
const dob = pixiApp.app.stage.addChild(subModel)

This does simply nothing. Is there a way to create a Model from a "sub"mesh?

**Comment by jnsmalm** [comment]
You don't need 6 different models to have separate animations. As default in glTF, animation are attached to a node/mesh, so they separate as default.

As a side note, a model is just a container for meshes and animations loaded from a file, so it actually doesn't make much sense to create a new model directly from code, although you could. Actually in your example you don't need to render the model at all, maybe you can do something like this?

```javascript
let model = PIXI3D.Model.from(resources["dice_models.gltf"].gltf))
let dice1 = model.meshes.filter(a => a.name === "dice1")

app.stage.addChild(dice1)
let animationForDice1 = model.animations.filter(a => a.name === "dice1_roll")
animationForDice1.play()
```

Just curious, isn't it easier to have 6 separate glTF models directly from 3d modeling tool?

**Comment by jnsmalm** [comment]
Just by looking at the source for a model, you realise it's almost nothing at all :)

https://github.com/jnsmalm/pixi3d/blob/develop/src/model.ts
