### ISSUE TITLE
Error: Extension class must have an extension object

### ISSUE THREAD

**Issue by Horsetoast** [jnsmalm/pixi3d#160]
Hi! I was trying to use pixi3d in React but can't even get a basic setup working. 
The error comes from https://pixijs.download/dev/docs/packages_extensions_src_index.ts.html line 79.
I'm not sure if this is pixi.js or pixi3d issue, but I could run pixi.js code just fine.

https://codesandbox.io/s/staging-leaf-6sho2x?file=/src/_app.js

**Comment by Horsetoast** [comment]
Hmm, it seems to work with pixi.js@6.X but not with version 7

**Comment by jnsmalm** [comment]
Hi!

When using PixiJS v.7+ you need to import from "pixi3d/pixi7" instead of "pixi3d", like this:

`import { Mesh3D } from "pixi3d/pixi7";`

**Comment by Horsetoast** [comment]
Thanks for the quick reply! When I tried that, it made me install `@pixi/assets@^7.1.2`. I did that, now I'm seeing a different bunch of errors. I haven't tinkered with it much, I'll try again when I get home.
![image](https://user-images.githubusercontent.com/4919815/218271162-f28567f3-001b-49a5-af8e-995e3f3ebc08.png)

**Comment by jnsmalm** [comment]
That's weird because I didn't change anything else then the import statement in your code and it worked.
