### ISSUE TITLE
iOS 16.4 rendering issue

### ISSUE THREAD

**Issue by StelyanBaltov** [jnsmalm/pixi3d#171]
Hello, I,ve noticed that there has been an issue with the 3d library and ios 16.4. All demo projects are broken. I cannot load the 3d models in my game as well. You can check pixi3d.org projects. I think it might be webgl 2.0 issue, but I'm not sure. 
The issue only happen on iphone with latest version - 16.4

**Comment by jnsmalm** [comment]
Thanks for reporting, I'll take a look!

**Comment by StelyanBaltov** [comment]
Tested and confirmed that it is working! Thank you so much for the quick fix!
