### ISSUE TITLE
3d Model and ImageBasedLighting visibility issue

### ISSUE THREAD

**Issue by StelyanBaltov** [jnsmalm/pixi3d#174]
Hello again :) I've noticed a glitch in the ImageBasedLighting or LightingEnvironment class. When you change model visibility to false and turn it back on in for example 3-4 minutes (that value is random, just turn visibility off for a long period of time), the image based lighting is gone. By gone I mean it's just not rendering anymore. The cubemap texture seem to stay in the LightingEnvironment.main object, but they are not applying on the 3d model anymore.

Cheers!

**Comment by jnsmalm** [comment]
Hello! Which version of PixiJS did you use when testing this?

**Comment by StelyanBaltov** [comment]
Hi, I did some more debugging. The issue happens in all version between 5.0.0 and 6.5.0. My game is using pixi version 5.3.10.

**Comment by jnsmalm** [comment]
Unfortunately this is a bug in PixiJS versions < 6.5.0. The fix in PixiJS was provided in https://github.com/pixijs/pixijs/pull/8479.

The bug happens on automatic gc inside PixiJS. If you can turn it off it should not happen. Try this in your app and see if it helps (depending on your app you might need to destroy your assets yourself if automatic gc won't do it):

`PIXI.settings.GC_MODES = PIXI.GC_MODES.MANUAL`

**Comment by StelyanBaltov** [comment]
Thank you! I'll look up the fix commit.
