### ISSUE TITLE
Textures smaller than 200x200 pixels do not render with Sprite3D

### ISSUE THREAD

**Issue by CopyCat85** [jnsmalm/pixi3d#177]
Using pixiJS v7.2.4 with pixi3d v2.3.1

```
// Does not work
let a = new PIXI3D.Sprite3D(commonAssets.rabbit1); // 25x25 PNG
let b = new PIXI3D.Sprite3D(commonAssets.rabbit2); // 199x199 PNG

// Works!
let c = new PIXI3D.Sprite3D(commonAssets.rabbit3); // 200x200 PNG
let d = new PIXI3D.Sprite3D(commonAssets.rabbit4); // 400x400 PNG
```

Many thanks for any ideas. Amazing library!

**Comment by jnsmalm** [comment]
Are those smaller sprites not just behind the larger ones?

This works for me (just a 32x32 size sprite):

```javascript
let sprite = app.stage.addChild(new PIXI3D.Sprite3D(PIXI.Texture.WHITE))
```

**Comment by CopyCat85** [comment]
Unfortunately not behind others either - I'm trying one at a time as well. The `PIXI.Texture.WHITE` (16x16) doesn't render on my `PIXI3D.Container3D` either. These sub 200x200 textures render fine on a normal 2D `PIXI.Container`. Thanks for the suggestion though, but I'm utterly stumped at the moment. This isn't a loader/browser issue - it _feeeeeels_ like a `PIXI3D.Container3D` on PixiJS 7.2.4 issue.

**Comment by CopyCat85** [comment]
Tried refactoring [this sample](https://codesandbox.io/s/github/jnsmalm/pixi3d-sandbox/tree/master/sprites-3d) locally with `7.2.4` and `2.3.1` but bunny textures are not showing for me. Wondering if anyone else can validate my possible madness?

**Comment by jnsmalm** [comment]
Would it be possible for you to provide a complete reproducable example so I can debug?

**Comment by jnsmalm** [comment]
> Tried refactoring [this sample](https://codesandbox.io/s/github/jnsmalm/pixi3d-sandbox/tree/master/sprites-3d) locally with `7.2.4` and `2.3.1` but bunny textures are not showing for me. Wondering if anyone else can validate my possible madness?

Are you running a local web server or are you just opening the html file in browser?

**Comment by CopyCat85** [comment]
Made a little demo. Needs a local web server... Hope this uploads! Thanks for looking!
[pixi3dtest-01.zip](https://github.com/jnsmalm/pixi3d/files/11242500/pixi3dtest-01.zip)

**Comment by jnsmalm** [comment]
Seems it doesn't works so well with this:

```javascript
PIXI.settings.ROUND_PIXELS = true; // Not sure if this does anything!
```

Remove that and it works, this setting isn't usable in 3D space anyways.

**Comment by CopyCat85** [comment]
Strange but true! Thank you for finding this. I didn't even consider the `ROUND_PIXELS` flag. I wonder why though.

**Comment by jnsmalm** [comment]
Found why this happens at https://github.com/jnsmalm/pixi3d/blob/fde244fc4054aeee4ad2c616ed4aea7e827785ab/src/sprite/projection-sprite.ts#L66

**Comment by CopyCat85** [comment]
I'm not seeing how your `round`-ing should be causing small textures to not render. Also:

- The general use case for PIXI's ROUND_PIXELS is good esp. for crisp text.
- I do see a use case where you might want blocky 3D - low-res retro 3D games.

**Comment by CopyCat85** [comment]
Another thought... As you initially mentioned, in a 3D context, ROUND_PIXELS is not relevant. In the use case where you do want no interpolation in a 3D view, then really we should be rendering to a PIXI texture anyway.

**Comment by CopyCat85** [comment]
Rendering a camera (even main) to a texture would be a very cool feature BTW.

**Comment by jnsmalm** [comment]
There is already a way to render to a texture, check https://api.pixi3d.org/classes/CompositeSprite.html and https://codesandbox.io/s/github/jnsmalm/pixi3d-sandbox/tree/master/post-processing-sprite
