### ISSUE TITLE
Boilerplate from create-pixi3d-app fails with PixiJs 7.2.4

### ISSUE THREAD

**Issue by choephix** [jnsmalm/pixi3d#181]
I created a fresh app with create-pixi3d-app, which works fine, but by now uses a slightly outdated version of PixiJs.

Upgrading to v 7.2.4, with no additional changes, produces the following Runtime errors:

![image](https://user-images.githubusercontent.com/962412/236046218-149c13d6-7790-403b-b5b8-d8ba11cf2f32.png)

(the parsers are failing, presumably because whatever way was registering them previously no longer works)

And the following typescript errors:

![image](https://user-images.githubusercontent.com/962412/236046633-71a87b90-29ed-449c-856b-6b653d62fc20.png)

![image](https://user-images.githubusercontent.com/962412/236046500-5f308b49-2da4-454a-9dc3-0b15b6913e24.png)

**Comment by jnsmalm** [comment]
Not sure what this error is. I tested with Pixi3D 2.3.2 and PixiJS 7.2.4 and it works. Can you try this command instead?

`npx create-pixi3d-app@latest <project_name>`

**Comment by choephix** [comment]
@jnsmalm You're right. I just tried again in a completely clean environment and it's working fine now. Sorry for my confusion, I'll close the issue, and look closer into what happened before. Thanks!
