### ISSUE TITLE
Greetings from pixi-projection!

### ISSUE THREAD

**Issue by ivanpopelyshev** [jnsmalm/pixi3d#2]
Subj.

I'm looking at your progress, and maybe i'll try to merge something with my architecture at pixi-projection.  My project lacks  glTF and actual 3d model support, but my ideas with containers and architecture surely can help.

For example, I know by experience that swapping 2d position to 3d in the same field can lead to many problems.

**Comment by jnsmalm** [comment]
Hello!

> For example, I know by experience that swapping 2d position to 3d in the same field can lead to many problems.

Do you have any specific use-case where it can lead to problems?
