### ISSUE TITLE
Events listners in models and custom camera (creating and moving)

### ISSUE THREAD

**Issue by joaodezembro** [jnsmalm/pixi3d#22]
Hi,

I need to listen to DOM Events in each model that i created (model creation on code below)
```
async renderTerrain() {
    for (let line = 0; line < this.#lines; line++) {
      for (let column = 0; column < this.#columns; column++) {
        const tile = new GameTile();
        await tile.loadAsset();
        tile.renderAsset();

        tile.mesh.position.x = line * 1.9;
        tile.mesh.position.z = column * 2;
        tile.mesh.meshes[1].alpha = 1;

        tile.mesh.interactive = true;
        tile.mesh.on('mouseover', (event) => {
          console.log('ok');
        });
      }
    }
  }
```

I tried to folow the following documentation (https://api.pixi3d.org/classes/model.html#interactivechildren) but without any success.

My goal is hide one mesh with alpha setted as 0 and when mouse hover this specific model, this mesh that was previously hide show again (only when hovering)

I'm also with some dificultes with the creation of custom cameras, for now i'm using the default internal camera created in CameraOrbitControl method. But i need create some cameras with specific world positions and angles and i couldn't create following the documentation

There is a print from working render from the code above
![image](https://user-images.githubusercontent.com/41813537/114649288-9ef88480-9cb6-11eb-8687-7fa1027013a2.png)

**Comment by jnsmalm** [comment]
Hi!

To be able to interact with models/meshes you need to also set a hit area using the PickingHitArea. The API for that is at https://api.pixi3d.org/classes/pickinghitarea.html and a simple example for how to use it can be found at https://github.com/jnsmalm/pixi3d/blob/develop/examples/src/mesh-interact.js

To be able to set the alpha for a mesh you have to set the baseColor on the material for that mesh (I'm presuming you are using the default standard material). You can see all properties at https://api.pixi3d.org/classes/standardmaterial.html. You also need to change the alpha mode for the material.

Something like:
```
mesh.material.alphaMode = "blend"
mesh.material.baseColor = [1, 1, 1, 0.5] // r, g, b, a
```
After describing this to you I realise I need to make it simpler to change the alpha value for an object :) I'll have a look at that.

You create a new camera with `let camera = new PIXI3D.Camera(app.renderer)`. After that you can just change the position/rotation of that camera anyway you want. If you want the same behaviour (orbiting) as CameraOrbitControl you can give it the camera when creating it `let control = new PIXI3D.CameraOrbitControl(app.view, camera)`.

If you don't want the user to be able to control the camera you can disable that by `control.allowControl = false`. You will still be able to control the camera with code using the angles `control.angles.x = 90` and `control, anglers.y = 25`.

To be able to set which camera is being used for rendering you can change the main camera by doing:
`PIXI3D.Camera.main = camera`

Let me know if you have any more issues/questions.

**Comment by joaodezembro** [comment]
Hi! Sorry the delay.

MeshInteract example it's perfect! Thanks!
Also, your example using alphaMode and baseColor solved my issue when creating a 3DMesh from scratch (without importing an object).

It's possible to get the XYZ position from the click?

Example,
I have a plane and i want to create a new mesh in the exact click position from my event.
(Obs: I have this X and Y inside the event callback (from event.data.global) but seems not to be the real location in the world)

![image](https://user-images.githubusercontent.com/41813537/114796104-762fc800-9d66-11eb-8abf-48c11bc6e55a.png)

**Comment by jnsmalm** [comment]
You can convert between screen/world coords by using https://api.pixi3d.org/classes/camera.html#screentoworld and https://api.pixi3d.org/classes/camera.html#worldtoscreen, not sure if that is enough for you. If you instead need a way to know where on a plane the click happened, you need to create a function to raycast to a plane (you will find plenty of sources for this). The raycast function is not build in Pixi3D as of now.

**Comment by jnsmalm** [comment]
Latest version 0.9.4 has now support for ray and plane. Using Camera.screenToRay, you should be able to do what you need.
