### ISSUE TITLE
PIXI Filters don't work with PIXI3D objects

### ISSUE THREAD

**Issue by vujadin** [jnsmalm/pixi3d#24]
PIXI3D objects don't have filterArea/bounds calculated so adding filters to them doesn't work.

**Comment by jnsmalm** [comment]
Just to get more context, what would you expect when applying a filter to a 3D object? Do you have a visual example?

One way of doing that today is to create a PostProcessingSprite (just a regular PixiJS sprite with extra functionality) and then apply filters to that one. Something like:

```javascript
let mesh = app.stage.addChild(Mesh3D.createCube())
let pipeline = StandardPipeline.from(app.renderer)

// All 3D objects will now render to the texture of this sprite by default
let sprite = pipeline.createPostProcessingSprite()

// Add any regular PixiJS filters you want
sprite.filters = [] 

app.addChild(sprite)
```

Not sure if this is enough?

**Comment by vujadin** [comment]
Here's visual example, getting-started example with GlowFilter:

![image](https://user-images.githubusercontent.com/4639385/115551982-0eb8d180-a2ac-11eb-8e71-310fe636e8ae.png)

**Comment by vujadin** [comment]
This works with these two lines:

![image](https://user-images.githubusercontent.com/4639385/115552167-44f65100-a2ac-11eb-9b4a-f12a9dce7963.png)

**Comment by vujadin** [comment]
Another visual, DotFilter

![image](https://user-images.githubusercontent.com/4639385/115552875-0f9e3300-a2ad-11eb-9f70-9c8211e941e8.png)

**Comment by jnsmalm** [comment]
It's easy to make it work for the entire object, more complicated if it should support have a filter covering just a part of the object. I guess it's ok, usually you want the entire object anyways - what do you think?

**Comment by jnsmalm** [comment]
I also noticed that adding filters to a 3D object clears the depth z-buffer after rendering that object. This can cause objects that should be behind another 3D object to instead be in front of it. Not sure anything can be done to fix that, I guess this is just how filters work in PixiJS. Can be good to know at least.

**Comment by jnsmalm** [comment]
Looking more at this I realised that PixiJS filters won't work well on 3D objects. By using filters, the object gets rendered to a texture instead of the screen directly. The render textures are not created to allow a depth buffer, which breaks the 3D objects. The solution for now is to use a PostProcessingSprite as explained above.
