### ISSUE TITLE
glft animated mesh animation time?

### ISSUE THREAD

**Issue by blurymind** [jnsmalm/pixi3d#3]
I see you have play and stop methods, but how does one increment animation time with this?

trying some rigged example gltf meshes from here
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0

all static, cant get them to play

**Comment by jnsmalm** [comment]
Unfortunately it doesn't support rigged animations yet. I'm working towards a v1.0 before moving on to that feature. 

It does support morphing and transformation animations though. For example, you can try it with https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphSphere and then: `model.animations[0].play()` and it will use the shared ticker in PixiJS and update the animation time.

**Comment by jnsmalm** [comment]
Oh, and the play feature is only in develop branch right now.

**Comment by blurymind** [comment]
ah I see, thats a shame :)

I look forward to getting that support :)
Nice work on this so far btw. Thanks for clarifying

**Comment by jnsmalm** [comment]
@blurymind I added support for rigged animations. You can check develop branch if you are still interested.

**Comment by blurymind** [comment]
Thank you for working on this. Its exciting to me from the angle of using a
3d mesh inside a 2d game. In this case the engine being gdevelop using this
library wrapped in an extension. And the other way around using 2d sprites
in a 3d world being the mesh.

I will give this a try and test it on a bunch of test examples :)

**Comment by jnsmalm** [comment]
Let me know if you have any feedback or run into problems!

**Comment by vujadin** [comment]
This is great! Congrats on a fantastic work!
The only thing missing is animation blending :) 
https://threejs.org/examples/webgl_animation_skinning_blending.html

**Comment by blurymind** [comment]
It would be fantastic if we can blend animations

**Comment by blurymind** [comment]
Hey thanks for building this as a UMD module btw - it should make it easier to test in gdevelop. Might try to use it to make an extension

But with this library it could become possible to create psOne era style games where 2d and 3d is blended. So it makes me wonder how much of the 2d pixi stuff can mesh with the 3d stuff

For example having a 3d model for the characters on a hand painted 2d background -like in the old final fantasy (7, 8 and 9) games. Of course that would require using the 3d camera and writing a mask shader to fake the character being behind objects that are a part of the 2d background. I wonder what the simplest way to achieve this would be

A simpler example would be just for a top down game where the character can move in 8 directions in a 2d world

Another example is the opposite - a 3d mesh that is used for the level and 2d sprites for the player/enemies

This is definitely something fun to explore and try to do with this library

**Comment by jnsmalm** [comment]
> For example having a 3d model for the characters on a hand painted 2d background -like in the old final fantasy (7, 8 and 9) games. Of course that would require using the 3d camera and writing a mask shader to fake the character being behind objects that are a part of the 2d background. I wonder what the simplest way to achieve this would be

For this, would it work having 3 layers? Background in 2D, characters in 3D and then foreground in 2D? Or the foreground objects could be in 3D, but just using mesh quads as sprites. Don't think you need to write a mask shader for this. Another way could be to render the 3D characters to a texture and then use that texture as a regular 2D sprite.

To mix 2D and 3D you could use the functions Camera.main.screenToWorld and Camera.main.worldToScreen.

**Comment by blurymind** [comment]
Thank you for implementing this! :) 🎉 🎉
