### ISSUE TITLE
PIXI v6

### ISSUE THREAD

**Issue by cvissie** [jnsmalm/pixi3d#36]
When using PIXI v6 there seems to be an issue with the depth buffer:

![image](https://user-images.githubusercontent.com/571532/127665841-a91ea500-1a93-4b34-be8d-e997c99d874f.png)

![image](https://user-images.githubusercontent.com/571532/127665942-78a90f2e-e8e5-4e81-b1e4-76f5d5fe50f9.png)

**Comment by jnsmalm** [comment]
Thanks for letting me know! It's was actually not a problem with the library, I noticed one of the materials for this model was incorrect. I have fixed this now. It should work fine for PixiJS 6+.

**Comment by cvissie** [comment]
Thank you for fixing! I was about to dig in and see if I can figure this out myself :)

Great library from what I have seen so far!
