### ISSUE TITLE
Changing alphaMode to 'blend' causes rendering problem since v0.9.6

### ISSUE THREAD

**Issue by andrej-ilic** [jnsmalm/pixi3d#39]
Try changing the version in the example to v0.9.5, where the model is rendered correctly.

Example: [https://codesandbox.io/s/pixi3d-097-3lb69](https://codesandbox.io/s/pixi3d-097-3lb69)

**v0.9.5**
<img src="https://user-images.githubusercontent.com/8559012/129200556-6eb69d62-1304-44fe-b3a5-86ad460a4717.png" alt="" width="200" height="200" />

**v0.9.7**
<img src="https://user-images.githubusercontent.com/8559012/129200554-6510d0fb-d0e8-41df-9c03-da623b4c0840.png" alt="" width="200" height="200" />

**Comment by jnsmalm** [comment]
Thanks, I'll take a look.

**Comment by jnsmalm** [comment]
For now you can solve it with:

```javascript
goalkeeper.meshes[0].material.alphaMode = "blend"
goalkeeper.meshes[0].material.state.depthMask = true
```

**Comment by jnsmalm** [comment]
I did some changes in develop branch, please let me know if this fixes your issue. You can clone the repo, then:
```
npm install
npm run build
```
You will find output in dist folder.

**Comment by andrej-ilic** [comment]
That fixed my issue. Thanks.
