### ISSUE TITLE
pixi3d destroy

### ISSUE THREAD

**Issue by siqi2006** [jnsmalm/pixi3d#40]
import { Mesh3D, Light, LightingEnvironment } from "pixi3d";

app.desdory(); // error.
↓
AbstractRenderer.prototype.destroy = function (removeView) {
        for (var o in this.plugins) {
            this.plugins[o].destroy(); // Here! this.plugins['lighting'].destroy is undefined.  and `this.plugins['picking'].destroy`.
            this.plugins[o] = null;
        }
        .
        .
        .
}

**Comment by jnsmalm** [comment]
Thanks! I have fixed this, it will come with next release.
