### ISSUE TITLE
Example.js is missing

### ISSUE THREAD

**Issue by Unwarped** [jnsmalm/pixi3d#47]
I wanted to test this out but it seems the .js file is missing in the examples folder.
Index.html:
`<script src="example.js"></script>`

**Comment by jnsmalm** [comment]
The example.js file only exist when the running the command explained at https://github.com/jnsmalm/pixi3d#examples

Before running that command you need to run npm install.

**Comment by Unwarped** [comment]
Excellent thank you jnsmalm.
Keep up the great work with Pixi3D I am really enjoying it so far. The integration right into PixiJS is really cool!

**Comment by jnsmalm** [comment]
Thanks!
