### ISSUE TITLE
CameraOrbitControl is not touch screen friendly

### ISSUE THREAD

**Issue by goldenratio** [jnsmalm/pixi3d#53]
is it possible to use `pointerdown` and `pointerup` so it's touch screen friendly?
https://github.com/jnsmalm/pixi3d/blob/develop/src/camera/camera-orbit-control.ts#L42

**Comment by jnsmalm** [comment]
Yes, want to do this but didn't have the time yet.

**Comment by lovelle-cardoso** [comment]
@goldenratio @jnsmalm I needed this feature too, so I made a pull request for it here: https://github.com/jnsmalm/pixi3d/pull/163

**Comment by jnsmalm** [comment]
Thanks @lovelle-cardoso ! Will be available in next release.

**Comment by jnsmalm** [comment]
@lovelle-cardoso When I try to use the orbit camera now I get an error in console (even though the functionality seems to work fine). I use a normal mouse/trackpad and macOS/Chrome. Would you have time to have a look?

<img width="747" alt="image" src="https://user-images.githubusercontent.com/10713751/224491279-748493bc-1242-4271-aec1-5b05a6663f8c.png">

**Comment by lovelle-cardoso** [comment]
@jnsmalm Sure thing! Should be fixed here: https://github.com/jnsmalm/pixi3d/pull/168

**Comment by lovelle-cardoso** [comment]
@jnsmalm Cleaned up PR here https://github.com/jnsmalm/pixi3d/pull/170
