### ISSUE TITLE
Skinning with many joints doesn't work on old weak devices

### ISSUE THREAD

**Issue by jnsmalm** [jnsmalm/pixi3d#58]
Maybe writing the joint matrices to a texture should be default?

**Comment by Unwarped** [comment]
Would the texture have to be updated every frame?
What sort of CPU/GPU impact could this have?
I would like to see this as an option but I know that would probably add some complexity supporting both. Multiple shaders etc.

**Comment by jnsmalm** [comment]
Yes, the texture have to be updated each frame. Pixi3D actually already supports storing joint matrix data in a texture for vertex skinning, otherwise it wouldn't work well to animate characters on a older mobile devices as they don't support enough vertex uniforms. Both Three.js and Babylon.js seems to store joint matrix data in a texture by default, so I think I Pixi3D can do that as well.

**Comment by Unwarped** [comment]
Hey jnsmalm. Just from watching GPU in task manager going from 18-20% on old version up to about 24-26% (about 25% jump).
Not the end of the world I know. Just alternating this build and one from a 1 or 2 back.
It's a 2D isometric demo I've been playing around with that has about a dozen animated 3D mesh characters on top.

**Comment by Unwarped** [comment]
Changing line 11,516 in my pixi3D build to 
`if (standard_material_matrix_texture_1.StandardMaterialMatrixTexture.isSupported(renderer) && 1 == 2) {`
seems to bring the numbers back down as a hack test.

**Comment by jnsmalm** [comment]
Not sure what the GPU in task manager actually measures. I render many skinned meshes and the performance seems to be exactly the same (using textures or uniforms) with this tool: https://github.com/mrdoob/stats.js/ I have tested both on Mac M1, iPhone 12 and an older weaker Android.

**Comment by Unwarped** [comment]
Yes I understand I see what you mean thanks jnsmalm.
How would you feel about a global PIXI variable to optionally enable/disable this behavior?

I abandoned my use of BabylonJS unfortunately as every little thing seemed to increase GPU usage until my simple demo with every optimization available was using 80% GPU and making my computer burning hot!

I admire how well Pixi3D is running with my project and don't want to add any unnecessary overhead. Many thanks for your responses and continued work on this project.

**Comment by jnsmalm** [comment]
Thanks for helping out with feedback, I'll see what I can do.

**Comment by jnsmalm** [comment]
Added a setting: `PIXI.settings.PREFER_UNIFORMS_WHEN_UPLOADING_SKIN_JOINTS = true`. Hope it helps.
