### ISSUE TITLE
No way to set animation loop to false or have onAnimationEnd event?

### ISSUE THREAD

**Issue by vujadin** [jnsmalm/pixi3d#6]
It would be great to have possibility to pass 'loop' parameter to animation.play() method (like anim.play(false) so it plays only once) and even better to be able to get noticed when animation has ended.

**Comment by jnsmalm** [comment]
Added a property for loop and on complete event. You can use it like this:

`animation.loop = true // default will be false`
`animation.on("complete", () => { console.log("animation complete") })`
`animation.play()`

It's available on develop branch, let me know if it is good enough :-)

**Comment by vujadin** [comment]
I've tried it and I have a few problems now:
animations[x].channels is gone, I have to use private prop (animations[x]._channels)

My animation has 65 frames but it fires "oncomplete" on frame no. 34 or 35:

```
currentPlayerAnimation.on("complete", (e) => {
	console.log(currentPlayerAnimation._channels[0].frame); 	// shows 34 or 35, but channel has 65 frames...
	player.visible = false;
});
```

My logic before was something like this:

(on every frame...)
```
if (currentKeeperAnimation.channels[0].frame === currentKeeperAnimation.channels[0].length - 2) {
    currentKeeperAnimation.stop();
    keeper.visible = false;
}
```

**Comment by vujadin** [comment]
animation.speed was set to 1.3 on one of my animations, maybe that's why it doesn't calculate correctly the end of animation?

**Comment by jnsmalm** [comment]
Please clone develop branch and do "npm install" and then "npm run serve -- --env.example=quick-guide"

Change the lines 32-37 to this  and see if it prints "complete"at the correct time in console:

```
model.animations[0].play()
  model.animations[0].loop = true
  model.animations[0].speed = 1.3
  model.animations[0].on("complete", () => {
    console.log("complete")
  })
```

**Comment by vujadin** [comment]
I have multiple animations on one mesh. Its in idle animation (and looping) until it needs to switch some other animation.
I had to stop idle animation before playing another, and that solved the problem. Thanks!
