### ISSUE TITLE
Is it possible to use spritesheet textures?

### ISSUE THREAD

**Issue by djlastnight** [jnsmalm/pixi3d#63]
Hello I have a problems with the model textures. If the texture comes from a spritesheet, the model displays the whole spritesheet instead of the proper texture. Here is the code, which I am using. Note that everything works perfectly fine, if I pass a 'standalone' texture.

```typescript
    public setTexture(meshIndex: number, texture: Texture) {
        let mat = this.model.meshes[meshIndex].material as StandardMaterial;
        mat.baseColorTexture = texture;
    }
```

**Comment by djlastnight** [comment]
I was able to fix this, using the following method, but it will be better if you add support for spritesheets either way.
```typescript
    public static extractFromSpriteSheet(textureName: string): Texture {
        let texture: Texture = Texture.from(textureName);
        let sprite: Sprite = new Sprite(texture);
        let options = {
            width: texture.width,
            height: texture.height
        };

        let baseRenderTexture: BaseRenderTexture = new BaseRenderTexture(options);
        let renderTexture: RenderTexture = new RenderTexture(baseRenderTexture);

        // Change this for your application
        let renderer: Renderer = App.instance.renderer;

        renderer.render(sprite, renderTexture);

        return renderTexture;
    }
```

**Comment by jnsmalm** [comment]
Hey!

You can also try using texture transform. In my example the sprite was rotated inside the sprite sheet, so you might need to adjust the calculations a bit. I'll see if I can support this automatically when setting the material texture.

```javascript
let texture = resources["assets/spritesheet.json"].textures["texture.png"]
texture.transform = new PIXI3D.TextureTransform()
texture.transform.offset.set(
  (texture.frame.x + texture.frame.width) / texture.baseTexture.width,
  (texture.frame.y + 0) / texture.baseTexture.height
)
texture.transform.scale.set(
  texture.frame.height / texture.baseTexture.height,
  texture.frame.width / texture.baseTexture.width
)
texture.transform.rotation = -90 * PIXI.DEG_TO_RAD

mesh.material.baseColorTexture = texture
```

**Comment by jnsmalm** [comment]
Added automatic support for spritesheet textures, will come in next release.

**Comment by djlastnight** [comment]
Thanks for the code. Actually my code has a huge memory leak, so I will try yours :)

**Comment by djlastnight** [comment]
I just tested the new feature - it works perfectly fine. In my particular case I grab animation frames from one or more spritesheets.
I had to set the spritesheet trim option to ```None```, otherwise I get strange results, because the sprites' transparent outermost part gets cut by texture packer to save space.

Anyway I am wondering do you have a solution for the following problem. See the image below.
![image](https://user-images.githubusercontent.com/19281127/144727970-50304fb2-a143-4692-936b-4a1fa6e19fec.png)

If I use alpha blend - the model textures looks nice, but got gramed.
If I use alpha clip - the models looks bad, but no frame around them is visible.
Any ideas?

**Comment by djlastnight** [comment]
I found you gave access to this programatically, which is awesome.
So I was able to workaround this as follows:
When I start the animation I change the blend mode to ```mask```, using ```alphaCutoff``` 0.80.
On animation complete, I simpy change back the blend mode to ```blend``` (which is the default for my models).
```typescript
    /**
     * Sets the material alpha blend mode.
     *
     * @param {number} meshIndex The mesh index, whose material's alpha mode to change.
     * @param {StandardMaterialAlphaMode} mode The new alpha blend mode.
     * @param {number} [alphaCutoff=0.8] The new alpha cutoff value,
     * in case StandardMaterialAlphaMode.mask mode is passed.
     * @memberof Model3D
     */
    public setAlphaMode(meshIndex: number, mode: StandardMaterialAlphaMode, alphaCutoff: number = 0.8) {
        let mat = this.model.meshes[meshIndex].material as StandardMaterial;
        mat.alphaMode = mode;
        if (mode == StandardMaterialAlphaMode.mask) {
            mat.alphaCutoff = Math.min(Math.max(0, alphaCutoff), 1);
        }
    }
```

**Comment by jnsmalm** [comment]
Curious, are you changing the texture of a mesh to play the animation frame by frame?

**Comment by djlastnight** [comment]
Yes, and actually runs very efficient and fast.
