### ISSUE TITLE
Remove the PostProcessingSprite handler from the shared ticker

### ISSUE THREAD

**Issue by amauryt** [jnsmalm/pixi3d#68]
Thank you for this great library. I am using it in the context of a Single Page Application (SPA), in which I need to create and destroy several PIXI apps within the lifecycle of the SPA. I noticed that the handler added by a PostProcessingSprite instance on [this line](https://github.com/jnsmalm/pixi3d/blob/c09ed9b0d4d2a67f836a888d0ba7274df0e3ccce/src/sprite/post-processing-sprite.ts#L62) is an anonymous function, which makes it pretty much impossible to remove from the PIXI shared ticker. This causes an error when destroying PIXI apps with PostProcessingSprite instances and creating other PIXI apps within the SPA.

When I encountered the error the first time I initially expected that by destroying the PostProcessingSprite instance the handler would be removed. Perhaps this could be a good solution without introducing breaking changes? That is, having the anonymous function to be a named function, which on destroying the sprite could now be removed from the shared ticker. Or perhaps there is another solution?

Thanks in advance!

**Comment by jnsmalm** [comment]
Hi and thank you for feedback, I'll create a fix for this!

**Comment by jnsmalm** [comment]
Might have found a fix for this. If you want to help out, you can get latest version from develop branch.

```
npm install
npm run build
```

You will find pixi3d.js in dist folder. Please let me know if this fixes your issues.

**Comment by amauryt** [comment]
That was quick! I just tested the develop branch directly on my app and it works: destroying the sprite removes the handler and I no longer see the error. Thank you!

**Comment by jnsmalm** [comment]
Fixed in v1.1.1
