### ISSUE TITLE
3D particles support

### ISSUE THREAD

**Issue by djlastnight** [jnsmalm/pixi3d#69]
Hi there, it's me again. I was wondering is the a way to use particles in 3d space. Example: the particles goes around a cylinder.
Thanks in advance.

**Comment by jnsmalm** [comment]
You create a bunch of Sprite3D objects and use as particles or if you want 3D objects, you can use instancing.
```javascript
let mesh = new Mesh3D(...)
let instance = mesh.createInstance()
```

**Comment by djlastnight** [comment]
got it, thanks :)
