### ISSUE TITLE
WebGL error: Too many uniforms

### ISSUE THREAD

**Issue by vujadin** [jnsmalm/pixi3d#7]
Here's an example of a skinned model that works in three.js but not in pixi3D (on iOS < 14):
https://threejs.org/examples/#webgl_animation_skinning_blending

Shaders couldn't compile, reporting too many uniforms...
Looks like three.js automatically reduces number of skinning weights:
https://discourse.threejs.org/t/is-the-limit-of-4-skinning-weights-per-vertex-a-hard-limit-of-webgl

Here's an issue reported on three.js: https://github.com/mrdoob/three.js/issues/7807

**Comment by jnsmalm** [comment]
Thanks! I'm currently looking into this actually.

**Comment by jnsmalm** [comment]
First, thanks for reporting these problems :-)

I might have a fix for the issue you are experiencing, please pull latest from develop branch and build it using "npm run build", pixi3d.js will be created in "dist" folder. Please let me know if this fixes the problem.

**Comment by vujadin** [comment]
Tested on a few iOS devices, works well on all of them. Thank you!
