### ISSUE TITLE
Pixi deprecation warning on render()

### ISSUE THREAD

**Issue by Friksel** [jnsmalm/pixi3d#79]
Using `PostProcessingSprite` pixi throws a deprecation Warning: 

``` text
Renderer#render arguments changed, use options instead.Deprecated since v6.0.0
```

Looks liks in this file: https://github.com/jnsmalm/pixi3d/blob/develop/src/sprite/post-processing-sprite.ts on line 85 

``` javascript
this.renderer.render(object, this._renderTexture)
```

the second argument needs to change to an options object.

pixi3d: 1.2.0

**Comment by jnsmalm** [comment]
Thanks! This is because I want to support PixiJS from v5.3 and since then the params has been changed. I have ignored it because it's just a warning. To fix this a check is needed which verifies the version of PixiJS is being used, I have not come around and done this yet.

**Comment by bencresty** [comment]
@jnsmalm  thanks!

**Comment by Friksel** [comment]
@jnsmalm  Thanks!
