### ISSUE TITLE
How it's different from Pixi Projection plugin?

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [jnsmalm/pixi3d#91]
Could you please explain in few words how Pixi3D is different from Pixi Projection plugin https://github.com/pixijs/pixi-projection?

**Comment by jnsmalm** [comment]
Pixi3D was created to render 3D objects in a 3D world. It can load models created with a 3D modelling tool like Blender or Maya.

Pixi-projection was created to display 2D images with a 3D perspective/projection. I have not used pixi-projection myself, so my explanation may be too simplified.

**Comment by dmitrykolesnikovich** [comment]
For project like Spades (card game)

![image](https://user-images.githubusercontent.com/6131040/162584412-8cf86c02-c808-4177-a162-327b30bdc199.png)

Would you suggest to use 2D plugin or your 3D renderer? Asking for a friend.

**Comment by jnsmalm** [comment]
Both will probably work. That game is simple enough to create a small prototype with both libs and then you can choose the one you like most.

**Comment by dmitrykolesnikovich** [comment]
Thanks!
