### ISSUE TITLE
Zooming in/out with CameraOrbitControl does not work in Firefox

### ISSUE THREAD

**Issue by Willem3141** [jnsmalm/pixi3d#95]
To reproduce, open [the teapot example](https://codesandbox.io/s/github/jnsmalm/pixi3d-sandbox/tree/master/quick-guide) with Firefox 99. Dragging to change the camera angle works, but scrolling does not. This works fine in Chrome.

This seems to be caused by the fact that Firefox does not implement the [non-standard](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event) `mousewheel` event which is used [here](https://github.com/jnsmalm/pixi3d/blob/develop/src/camera/camera-orbit-control.ts#L56) to implement zooming.

**Comment by jnsmalm** [comment]
Thanks, will take a look!
